### ISSUE TITLE
TypeError: model.dest.plural.replaceAll is not a function

### ISSUE THREAD

**Issue by negati-ve** [eharain/strapi3to4migration#1]
strapi3to4migration % node index.js
/Users/userA/Lab/strapi3to4migration/helpers/migration-helper.js:104
                    model.dest.plural = model.dest.plural.replaceAll('_', '-');
                                                          ^

TypeError: model.dest.plural.replaceAll is not a function
    at /Users/userA/Lab/strapi3to4migration/helpers/migration-helper.js:104:59
    at Array.map (<anonymous>)
    at Object.pathToStrapi3Source (/Users/userA/Lab/strapi3to4migration/helpers/migration-helper.js:72:39)
    at /Users/userA/Lab/strapi3to4migration/lib.js:110:54
    at Array.map (<anonymous>)
    at Object.loadStrapi3SourceMatches (/Users/userA/Lab/strapi3to4migration/lib.js:110:31)
    at migrate (/Users/userA/Lab/strapi3to4migration/index.js:24:28)
    at Object.<anonymous> (/Users/userA/Lab/strapi3to4migration/index.js:78:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

**Comment by negati-ve** [comment]
package.json specifies engines >=12.22.0 <=16.x.x

replaceAll is supported after node v15 

Just going to leave this here in case anyone faces this issue
