### ISSUE TITLE
no such file or directory, scandir '.../strapi-v3/components

### ISSUE THREAD

**Issue by negati-ve** [eharain/strapi3to4migration#2]
script fails if v3 repo has no components

Error: ENOENT: no such file or directory, scandir '/Users/x/Lab/strapi-v3/components'
    at Object.readdirSync (node:fs:1057:3)
    at Object.getFileslist (/Users/x/Lab/strapi3to4migration/helpers/migration-utils.js:66:37)
    at Object.pathToStrapi3Source (/Users/x/Lab/strapi3to4migration/helpers/migration-helper.js:72:14)
    at /Users/x/Lab/strapi3to4migration/lib.js:110:54
    at Array.map (<anonymous>)
    at Object.loadStrapi3SourceMatches (/Users/x/Lab/strapi3to4migration/lib.js:110:31)
    at migrate (/Users/x/Lab/strapi3to4migration/index.js:24:28)
    at Object.<anonymous> (/Users/x/Lab/strapi3to4migration/index.js:78:1)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/x/Lab/strapi-v3/components'
}

**Comment by negati-ve** [comment]
simple temporary fix is to comment out 
` { location: "components", apiPrefix: "" },`
in config/settings.js
